### ISSUE TITLE
Single char edit

### ISSUE THREAD

**Issue by AntonioFromBrazil** [tchapi/Adafruit-GFX-Font-Customiser#7]
Hello tchap, congratulations for your excellent job. As a suggestion I wonder if there is a single character edit function, with a large screen and large pixels... Do you think it would be usefull ?

**Comment by tchapi** [comment]
Hi
There is no such feature at the moment, but if you think this would be useful, I'm accepting a PR for that ;)

I have not much time at the moment to dive into this personally. You could just make a few CSS changes to make the "pixels" bigger on the page though, this should work.
Best regards

**Comment by AntonioFromBrazil** [comment]
Good ideia. I will try. Thanks a lot !

**Comment by AntonioFromBrazil** [comment]
Good ideia. I will try. Thanks a lot !

**Comment by AntonioFromBrazil** [comment]
tchapi, your idea was ALMOST successfull...  Changing CSS table tr height: to e.g 30px; and table width: to e.g 30px; we increased the pixel size accordinly. But it insist on have two table colluns (not one as desired) and I could not find a way to enable the browser horizontal scroll bar .... Could you please give me some help on that issues ? Thanks a lot

**Comment by tchapi** [comment]
I'm not really sure I understand your point. The CSS works as expected for the table "pixels"; if you want to have _less_ characters per line, though, you can change the column split (we use semantic-ui) by changing that lines https://github.com/tchapi/Adafruit-GFX-Font-Customiser/blob/master/index.html#L301 

Instead of `two`, change it to `four` or `six`, to have less characters per line

Is that what you wanted to achieve ?

**Comment by AntonioFromBrazil** [comment]
Great ! Thanks so much. The page is working now as I desired.

**Comment by tchapi** [comment]
👍
